apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydeploy-pv
spec:
  storageClassName: "mydeploysc"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv0002/