apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydeploy
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
          - name: mydeploy-pvc
            mountPath: /pvc
      volumes:
        - name: cache-volume
          emptyDir:
           medium: Memory
        - name: mydeploy-pvc
          persistentVolumeClaim:
           claimName: mydeploy-pvc
